
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const provider = (process.env.DATABASE_PROVIDER ?? "sqlite").toLowerCase();
const schemaPath =
  provider === "postgresql" ? "prisma/schema.postgres.prisma" : "prisma/schema.prisma";

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
